echo "FUZZING THROUGH FFUF"
awk '{$0=$0"/FUZZ"}1' HTTPX.txt >> allHTTPX.txt
cat allHTTPX.txt | while read url;do ffuf -w /home/himanshu/payloads/bruteforce-lists/adminer.txt -u "$url" -v;done | tee -a adminer.txt
cat allHTTPX.txt | while read url;do ffuf -w /home/himanshu/payloads/bruteforce-lists/api.txt -u "$url" -v;done | tee -a api.txt
cat allHTTPX.txt | while read url;do ffuf -w /home/himanshu/payloads/bruteforce-lists/apk.txt -u "$url" -v;done | tee -a apk.txt
cat allHTTPX.txt | while read url;do ffuf -w /home/himanshu/payloads/bruteforce-lists/asax.txt -u "$url" -v;done | tee -a asax.txt
cat allHTTPX.txt | while read url;do ffuf -w /home/himanshu/payloads/bruteforce-lists/ashx.txt -u "$url" -v;done | tee -a ashx.txt
cat allHTTPX.txt | while read url;do ffuf -w /home/himanshu/payloads/bruteforce-lists/asmx.txt -u "$url" -v;done | tee -a asmx.txt
cat allHTTPX.txt | while read url;do ffuf -w /home/himanshu/payloads/bruteforce-lists/asp.txt -u "$url" -v;done | tee -a asp.txt
cat allHTTPX.txt | while read url;do ffuf -w /home/himanshu/payloads/bruteforce-lists/aspx.txt -u "$url" -v;done | tee -a aspx.txt
cat allHTTPX.txt | while read url;do ffuf -w /home/himanshu/payloads/bruteforce-lists/cgi-bin.txt -u "$url" -v;done | tee -a cgi-bin.txt
cat allHTTPX.txt | while read url;do ffuf -w /home/himanshu/payloads/bruteforce-lists/cgi-files.txt -u "$url" -v;done | tee -a cgi.txt
cat allHTTPX.txt | while read url;do ffuf -w /home/himanshu/payloads/bruteforce-lists/config.txt -u "$url" -v;done | tee -a config.txt
cat allHTTPX.txt | while read url;do ffuf -w /home/himanshu/payloads/bruteforce-lists/csproj.txt -u "$url" -v;done | tee -a csproj.txt
cat allHTTPX.txt | while read url;do ffuf -w /home/himanshu/payloads/bruteforce-lists/dotfiles.txt -u "$url" -v;done | tee -a dotfiles.txt
cat allHTTPX.txt | while read url;do ffuf -w /home/himanshu/payloads/bruteforce-lists/ec2.txt -u "$url" -v;done | tee -a ec2.txt
cat allHTTPX.txt | while read url;do ffuf -w /home/himanshu/payloads/bruteforce-lists/env.txt -u "$url" -v;done | tee -a env.txt
cat allHTTPX.txt | while read url;do ffuf -w /home/himanshu/payloads/bruteforce-lists/git_config.txt -u "$url" -v;done | tee -a git_config.txt
cat allHTTPX.txt | while read url;do ffuf -w /home/himanshu/payloads/bruteforce-lists/honey.txt -u "$url" -v;done | tee -a honey.txt
cat allHTTPX.txt | while read url;do ffuf -w /home/himanshu/payloads/bruteforce-lists/htaccess -u "$url" -v;done | tee -a htaccess.txt
cat allHTTPX.txt | while read url;do ffuf -w /home/himanshu/payloads/bruteforce-lists/htm.txt -u "$url" -v;done | tee -a htm.txt
cat allHTTPX.txt | while read url;do ffuf -w /home/himanshu/payloads/bruteforce-lists/iso.txt -u "$url" -v;done | tee -a iso.txt
cat allHTTPX.txt | while read url;do ffuf -w /home/himanshu/payloads/bruteforce-lists/k8s.txt -u "$url" -v;done | tee -a k8s.txt
cat allHTTPX.txt | while read url;do ffuf -w /home/himanshu/payloads/bruteforce-lists/keys.txt -u "$url" -v;done | tee -a keys.txt
cat allHTTPX.txt | while read url;do ffuf -w /home/himanshu/payloads/bruteforce-lists/log.txt -u "$url" -v;done | tee -a log.txt
cat allHTTPX.txt | while read url;do ffuf -w /home/himanshu/payloads/bruteforce-lists/needstobefixed.txt -u "$url" -v;done | tee -a needstobefixed.txt
cat allHTTPX.txt | while read url;do ffuf -w /home/himanshu/payloads/bruteforce-lists/npmrc.txt -u "$url" -v;done | tee -a npmrc.txt
cat allHTTPX.txt | while read url;do ffuf -w /home/himanshu/payloads/bruteforce-lists/params.txt -u "$url" -v;done | tee -a params.txt
cat allHTTPX.txt | while read url;do ffuf -w /home/himanshu/payloads/bruteforce-lists/pdfs.txt -u "$url" -v;done | tee -a pdfs.txt
cat allHTTPX.txt | while read url;do ffuf -w /home/himanshu/payloads/bruteforce-lists/peoplesoft.txt -u "$url" -v;done | tee -a peoplesoft.txt
cat allHTTPX.txt | while read url;do ffuf -w /home/himanshu/payloads/bruteforce-lists/perl-files.txt -u "$url" -v;done | tee -a perl.txt
cat allHTTPX.txt | while read url;do ffuf -w /home/himanshu/payloads/bruteforce-lists/phpmyadmin.txt -u "$url" -v;done | tee -a phpmyadmin.txt
cat allHTTPX.txt | while read url;do ffuf -w /home/himanshu/payloads/bruteforce-lists/php.txt -u "$url" -v;done | tee -a php.txt
cat allHTTPX.txt | while read url;do ffuf -w /home/himanshu/payloads/bruteforce-lists/phpunit.txt -u "$url" -v;done | tee -a phpunit.txt
cat allHTTPX.txt | while read url;do ffuf -w /home/himanshu/payloads/bruteforce-lists/properties-files.txt -u "$url" -v;done | tee -a properties.txt
cat allHTTPX.txt | while read url;do ffuf -w /home/himanshu/payloads/bruteforce-lists/reallysafe-not.txt -u "$url" -v;done | tee -a reallysafe.txt
cat allHTTPX.txt | while read url;do ffuf -w /home/himanshu/payloads/bruteforce-lists/sql.txt -u "$url" -v;done | tee -a sql.txt
cat allHTTPX.txt | while read url;do ffuf -w /home/himanshu/payloads/bruteforce-lists/svc.txt -u "$url" -v;done | tee -a svc.txt
cat allHTTPX.txt | while read url;do ffuf -w /home/himanshu/payloads/bruteforce-lists/wad.txt -u "$url" -v;done | tee -a wad.txt
cat allHTTPX.txt | while read url;do ffuf -w /home/himanshu/payloads/bruteforce-lists/webconfig.txt -u "$url" -v;done | tee -a webconfig.txt
cat allHTTPX.txt | while read url;do ffuf -w /home/himanshu/payloads/bruteforce-lists/web-inf.txt -u "$url" -v;done | tee -a inf.txt
cat allHTTPX.txt | while read url;do ffuf -w /home/himanshu/payloads/bruteforce-lists/windows-lfi.txt -u "$url" -v;done | tee -a lfi.txt
cat allHTTPX.txt | while read url;do ffuf -w /home/himanshu/payloads/bruteforce-lists/wordpress-random.txt -u "$url" -v;done | tee -a random.txt
cat allHTTPX.txt | while read url;do ffuf -w /home/himanshu/payloads/bruteforce-lists/wp-content.txt -u "$url" -v;done | tee -a content.txt
cat allHTTPX.txt | while read url;do ffuf -w /home/himanshu/payloads/bruteforce-lists/yaml.txt -u "$url" -v;done | tee -a yaml.txt
cat allHTTPX.txt | while read url;do ffuf -w /home/himanshu/payloads/bruteforce-lists/zip.txt -u "$url" -v;done | tee -a zip.txt
